---
name: pcap

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm
  - name: bosh-dns-aliases
    jobs:
      - name: bosh-dns-aliases
        release: bosh-dns-aliases
        properties:
          aliases:
            - domain: nats.service.cf.internal
              targets:
                - deployment: cf
                  domain: bosh
                  instance_group: nats
                  network: cf
                  query: '*'
            - domain: _.nats.service.cf.internal
              targets:
                - deployment: cf
                  domain: bosh
                  instance_group: nats
                  network: cf
                  query: _
instance_groups:
  - name: pcap-api
    azs:
      - z1
    instances: 2
    vm_type: ((pcap_api.vm_type))
    stemcell: default
    networks: ((pcap_api.networks))
    jobs:
      - name: pcap-api
        release: pcap
        properties:
          pcap-api:
            log_level: info
            buffer:
              size: 1000
              upper_limit: 995
              lower_limit: 900
            concurrent_captures: 5
            listen:
              port: 8080
              tls:
                certificate: ((pcap_api_mtls.certificate))
                private_key: ((pcap_api_mtls.private_key))
                ca: ((pcap_ca.ca))
            bosh:
              director_url: ((pcap_api.bosh_director_api))
              token_scope: bosh.admin
              agent_port: 9494
              mtls:
                common_name: bosh.service.cf.internal
                skip_verify: true
                certificate: ((pcap_api_bosh_mtls.certificate))
                private_key: ((pcap_api_bosh_mtls.certificate))
                ca: ((/bootstrap-bosh-aws-cfn07/bosh/default_ca.ca))
            agents_mtls:
              enabled: false
      - name: route_registrar
        release: routing
        consumes:
          nats-tls:
            from: nats-tls
            deployment: cf
        properties:
          route_registrar:
            routes:
              - name: pcap-api-public-endpoint
                registration_interval: 20s
                port: 8080
                uris:
                  - ((route_registrar.public_route))
            port: 8080
          nats:
            tls:
              enabled: true
              client_cert: ((nats.client_cert))
              client_key: ((nats.client_key))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-bionic
    version: latest

releases:
  - name: bpm
    version: 1.1.8
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
    sha1: c956394fce7e74f741e4ae8c256b480904ad5942
  - name: pcap
    version: 0+dev.30
  - name: bosh-dns-aliases
    version: 0.0.4
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.4
    sha1: 55b3dced813ff9ed92a05cda02156e4b5604b273
  - name: routing
    version: 0.232.0
    url: https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.232.0
    sha1: 1150a7c89a04db07145c906ccdbfda7424e6dfc6

variables:
  - name: pcap_api_mtls
    type: certificate
    options:
      ca: ((pcap_api.ca_path))
      common_name: pcap_api_mtls
      alternative_names:
        - pcap-api.service.cf.internal
      extended_key_usage:
        - client_auth
        - server_auth
  - name: pcap_api_bosh_mtls
    type: certificate
    options:
      ca: ((pcap_api.bosh_director_ca))
      common_name: pcap_api_bosh_mtls
      alternative_names:
        - pcap-api.service.cf.internal
      extended_key_usage:
        - client_auth
