---
- type: replace
  path: /releases/name=bosh-dns-aliases?
  value:
    name: bosh-dns-aliases
    version: 0.0.4
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.4
    sha1: 55b3dced813ff9ed92a05cda02156e4b5604b273

- type: replace
  path: /addons?/-
  value:
    include:
      instance_groups:
        - web
    name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
        - domain: nats.service.cf.internal
          targets:
            - deployment: cf
              domain: bosh
              instance_group: nats
              network: cf
              query: "*"
        - domain: _.nats.service.cf.internal
          targets:
            - deployment: cf
              domain: bosh
              instance_group: nats
              network: cf
              query: _
